import Foundation

struct Localization {
    static let map: [String: String] = [
        // COMMON ACTIONS
        "Delete input": "Supprimer l'entrée",
        "Import": "Import",
        "Delete Resource": "Supprimer Ressource",
        "Are you sure you want to remove this resource source?": "Voulez-vous vraiment supprimer cette source de ressource ?",
        "Delete": "Supprimer",

        // ORES
        "Iron Ore": "Minerai de Fer",
        "Copper Ore": "Minerai de Cuivre",
        "Limestone": "Calcaire",
        "Coal": "Charbon",
        "Caterium Ore": "Minerai de Caterium",
        "Raw Quartz": "Quartz Brut",
        "Sulfur": "Soufre",
        "Bauxite": "Bauxite",
        "Uranium": "Uranium",

        // FLUIDS
        "Water": "Eau",
        "Oil": "Pétrole Brut",
        "Heavy Oil Residue": "Résidu d'Huile Lourde",
        "Nitrogen Gas": "Azote",
        "Sulfuric Acid": "Acide Sulfurique",
        "Fuel": "Carburant",
        "Turbofuel": "Turbocarburant",
        "Alumina Solution": "Solution d'Alumine",

        // INGOTS
        "Iron Ingot": "Lingot de Fer",
        "Copper Ingot": "Lingot de Cuivre",
        "Steel Ingot": "Lingot d'Acier",
        "Caterium Ingot": "Lingot de Caterium",
        "Aluminum Ingot": "Lingot d'Aluminium",

        // PARTS
        "Concrete": "Béton",
        "Iron Plate": "Plaque de Fer",
        "Iron Rod": "Tige de Fer",
        "Screw": "Vis",
        "Reinforced Iron Plate": "Plaque de Fer Renforcée",
        "Wire": "Fil Électrique",
        "Cable": "Câble",
        "Quickwire": "Fil Actif",
        "Copper Sheet": "Tôle de Cuivre",
        "Alclad Aluminum Sheet": "Tôle d'Aluminium",
        "Aluminum Casing": "Boîtier en Aluminium",
        "Steel Beam": "Poutre en Acier",
        "Steel Pipe": "Tuyau en Acier",
        "Encased Industrial Beam": "Poutre en Béton Armé",
        "Modular Frame": "Cadre Modulaire",
        "Heavy Modular Frame": "Cadre Modulaire Lourd",
        "Fused Modular Frame": "Cadre Modulaire Fusionné",
        "Rotor": "Rotor",
        "Stator": "Stator",
        "Motor": "Moteur",
        "Turbo Motor": "Turbo Moteur",
        "Plastic": "Plastique",
        "Rubber": "Caoutchouc",
        "Quartz Crystal": "Cristal de Quartz",
        "Silica": "Silice",
        "Circuit Board": "Circuit Imprimé",
        "AI Limiter": "Limiteur IA",
        "High-Speed Connector": "Connecteur Haute Vitesse",
        "Computer": "Ordinateur",
        "Supercomputer": "Superordinateur",
        "Crystal Oscillator": "Oscillateur à Cristal",
        "Radio Control Unit": "Unité de Contrôle Radio",
        "Heat Sink": "Dissipateur Thermique",
        "Cooling System": "Système de Refroidissement",
        "Battery": "Batterie",
        "Electromagnetic Control Rod": "Barre de Contrôle Électromagnétique",
        "Smart Plating": "Plaquage Intelligent",
        "Versatile Framework": "Structure Polyvalente",
        "Automated Wiring": "Câblage Automatisé",
        "Modular Engine": "Moteur Modulaire",
        "Adaptive Control Unit": "Unité de Contrôle Adaptative",
        "Magnetic Field Generator": "Générateur de Champ Magnétique",
        "Thermal Propulsion Rocket": "Fusée à Propulsion Thermique",
        "Aluminum Scrap": "Déchets d'Aluminium",

        // BUILDINGS
        "Smelter": "Fonderie",
        "Foundry": "Fonderie Avancée",
        "Constructor": "Constructeur",
        "Assembler": "Façonneuse",
        "Manufacturer": "Façonneuse Industrielle",
        "Refinery": "Raffinerie",
        "Packager": "Conditionneuse",
        "Blender": "Mélangeur",
        "Particle Accelerator": "Accélérateur de Particules",
        "Coal Generator": "Générateur à Charbon",
        "Fuel Generator": "Générateur à Carburant",
        "Nuclear Power Plant": "Centrale Nucléaire",

        // RECIPES (Alternates often have "Alternate: " prefix or specific names)
        "Cast Screw": "Vis Moulée",
        "Stitched Iron Plate": "Plaque de Fer Cousue",

        // UI TERMS
        "Resource Node": "Noeud de Ressource",
        "Input": "Entrée",
        "Output": "Sortie",
        "Machine": "Machine",
        "SINK OVERFLOW": "BROYEUR (SURPLUS)",
        "FINAL PRODUCT": "PRODUIT FINAL",

        // TAB BAR
        "HUB": "HUB",
        "Resources": "Ressources",
        "Factory": "Usine",
        "Power": "Énergie",
        "Library": "M.A.M.",
        "Flow": "Flux",
        "Calculator": "Calculateur",
        "Tools": "Outils",
        "Database": "Base de Données",
        "To-Do": "Tâches",
        "Settings": "Paramètres",

        // DASHBOARD
        "WELCOME, PIONEER": "BIENVENUE, PIONNIER",
        "GRID STATUS": "ÉTAT DU RÉSEAU",
        "CALCULATING...": "CALCUL EN COURS...",
        "OPERATIONAL": "OPÉRATIONNEL",
        "ACTIVE GOALS": "OBJECTIFS ACTIFS",
        "IDLE": "EN ATTENTE",
        "A.W.E.S.O.M.E. SINK": "BROYEUR A.W.E.S.O.M.E.",
        "POINTS/MIN": "POINTS/MIN",
        "via": "via",
        "NO OVERFLOW": "AUCUN SURPLUS",
        "Quick Actions": "Actions Rapides",
        "New Project": "Nouveau Projet",
        "Notes": "Notes",
        "others...": "autres...",

        // HUB (NEW)
        "Search database...": "Rechercher...",
        "SEARCH RESULTS": "RÉSULTATS DE RECHERCHE",
        "No results found.": "Aucun résultat trouvé.",
        "Clear search": "Effacer la recherche",
        "Double tap to show details": "Toucher deux fois pour voir les détails",
        "FICSIT FACTORY OS": "FICSIT FACTORY OS",
        "GLOBAL COMMAND": "COMMANDEMENT GLOBAL",
        "ACTIVE FACTORIES": "USINES ACTIVES",
        "Production Sites": "Sites de Production",
        "Establish New Site": "Établir Nouveau Site",
        "New Factory": "Nouvelle Usine",
        "Name": "Nom",
        "Create": "Créer",
        "Enter designation for the new production site.": "Entrez la désignation du nouveau site de production.",
        "ONLINE": "EN LIGNE",
        "FICSIT OS": "SYSTÈME FICSIT",
        "DASHBOARD": "TABLEAU DE BORD",
        "CURRENT PROJECT": "PROJET ACTUEL",
        "ALL PROJECTS": "TOUS LES PROJETS",
        "Project Name": "Nom du Projet",
        "PLANNING TOOLS": "OUTILS DE PLANIFICATION",
        "Extraction Calculator": "Calculateur d'Extraction",
        "Blueprint Library": "Bibliothèque de Plans",
        "Logistics Planner": "Planificateur Logistique",
        "Search Items & Recipes...": "Chercher Items & Recettes...",

        // INPUT VIEW
        "RESOURCE SURVEY": "SURVEY RESSOURCES",
        "ADD SOURCE": "AJOUTER SOURCE",
        "Claimed Sources": "Sources Revendiquées",
        "No scanned resources.": "Aucune ressource scannée.",
        "No resources configured.": "Aucune ressource configurée.",
        "Belt Level": "Niveau de Convoyeur",
        "Cancel": "Annuler",
        "Save": "Sauver",
        "RESOURCE TYPE": "TYPE DE RESSOURCE",
        "Select Resource": "Choisir Ressource",
        "NODE PURITY": "PURETÉ DU NOEUD",
        "MINER LEVEL": "NIVEAU DE MINEUR",
        "EXTRACTION RATE": "DÉBIT EXTRACTION",
        "Add Source": "Ajouter Source",
        "Edit Source": "Modifier Source",
        "Logistics Import": "Import Logistique",
        "SOURCE FACTORY": "USINE SOURCE",
        "No other factories available.": "Aucune autre usine disponible.",
        "Select Factory...": "Sélectionner Usine...",
        "This will import resources produced by the selected factory.": "Ceci importera les ressources produites par l'usine sélectionnée.",

        // OUTPUT VIEW
        "PRODUCTION MANAGEMENT": "GESTION DE PRODUCTION",
        "Select Part...": "Sélectionner Pièce...",
        "CALCULATE": "CALCULER",
        "ERROR": "ERREUR",
        "POWER USAGE": "CONSO ÉLECTRIQUE",
        "REAL OUTPUTS": "SORTIES RÉELLES",
        "Insufficient resources or bottleneck detected.": "Ressources insuffisantes ou goulot d'étranglement détecté.",
        "Target Ratio": "Ratio Cible",
        "Delete Goal": "Supprimer Objectif",
        "Edit Goal": "Modifier Objectif",

        // SHOPPING LIST
        "SHOPPING LIST": "Liste d'Achats",
        "No materials required": "Aucun matériel requis",
        "Calculate a plan first.": "Calculez d'abord un plan.",
        "CONSTRUCTION MATERIALS": "MATÉRIAUX DE CONSTRUCTION",
        "Close": "Fermer",

        // RECIPE LIBRARY
        "M.A.M. LIBRARY": "BIBLIOTHÈQUE M.A.M.",
        "active": "active",

        // POWER PLANNER
        "GRID MONITOR": "MONITEUR DE RÉSEAU",
        "Balance production vs consumption.": "Équilibrer production vs consommation.",
        "FUEL TYPE": "TYPE DE CARBURANT",
        "AVAILABLE AMOUNT": "QUANTITÉ DISPONIBLE",
        "UPDATE GRID": "METTRE À JOUR RÉSEAU",
        "OVERLOAD": "SURCHARGE",
        "STABLE": "STABLE",
        "Load": "Charge",
        "Cons": "Conso",
        "Water Required": "Eau Requise",
        "Extractors": "Extracteurs",
        "Power Failure Imminent! Add": "Panne imminente! Ajoutez",
        "Reserve Capacity": "Capacité de réserve",
        "Enter fuel amount to simulate.": "Entrez une quantité de carburant pour simuler.",

        // PROJECT MANAGER
        "PROJECT MANAGER": "Gestion de Projets",
        "No saved projects": "Aucun projet sauvegardé",
        "Modified": "Modifié le",
        "SAVE PROJECT": "SAUVEGARDER PROJET",
        "NEW EMPTY PROJECT": "NOUVEAU PROJET VIDE",
        "Save Project": "Sauvegarder Projet",
        "Enter a name for your factory.": "Entrez un nom pour votre usine.",

        // BOTTLENECK SUGGESTIONS
        "Add more nodes for": "Ajouter un nœud supplémentaire de",
        "Use a Pure node for": "Utiliser un nœud Pur de",
        "Upgrade Miner to Mk3": "Améliorer le foreur à Mk3",
        "Increase production of": "Augmenter la production de",
        "Check alternate recipes": "Vérifier les recettes alternatives",
        "Verify Mk5 belts are used": "Vérifier que les convoyeurs Mk5 sont utilisés",

        // BLUEPRINT
        "BLUEPRINT": "PLAN",
        "Splitter/Merger": "Répartiteur/Groupeur",
        "BLUEPRINTS": "PLANS",
        "LIBRARY": "BIBLIOTHÈQUE",
        "No Blueprints Saved": "Aucun Plan Sauvegardé",
        "Save your factory plans as blueprints to reuse them later.": "Sauvegardez vos plans d'usine pour les réutiliser plus tard.",

        // TO-DO LIST
        "TO-DO LIST": "LISTE DE TÂCHES",
        "Add New Task": "Ajouter Nouvelle Tâche",
        "Task Description": "Description de la Tâche",
        "Category (Optional)": "Catégorie (Optionnel)",
        "Priority": "Priorité",
        "Normal": "Normal",
        "High": "Élevée",
        "Add": "Ajouter",
        "General": "Général",
        "HIGH PRIORITY": "HAUTE PRIORITÉ",
        "No tasks pending.": "Aucune tâche en attente.",
        "Add construction tasks to track your progress.": "Ajoutez des tâches de construction pour suivre votre progression.",
        "Add new task": "Ajouter une nouvelle tâche",
        "Mark as completed": "Marquer comme terminée",
        "Mark as incomplete": "Marquer comme inachevée",
        "TASK LOG": "JOURNAL DES TÂCHES",
        "CONSTRUCTION TASKS": "TÂCHES DE CONSTRUCTION",
        "Search tasks...": "Chercher tâches...",
        "All": "Tout",
        "In Progress": "En Cours",
        "Complete": "Terminé",
        "No tasks found": "Aucune tâche trouvée",
        "Task Details": "Détails de la Tâche",
        "New Task": "Nouvelle Tâche",

        // EXTRACTION
        "RESOURCE EXTRACTION": "EXTRACTION RESSOURCES",
        "MINING CALCULATOR": "CALCULATEUR MINIER",
        "Target Resource": "Ressource Cible",
        "Change": "Changer",
        "Configuration": "Configuration",
        "Node Purity": "Pureté du Noeud",
        "Miner Tier": "Niveau Mineur",
        "Clock Speed": "Vitesse d'Horloge",
        "Output Analysis": "Analyse de Sortie",
        "Power Usage": "Usage Électrique",
        "Global Sustainability": "Durabilité Globale",
        "Map Availability for": "Disponibilité Carte pour",
        "Impure": "Impur",
        "Pure": "Pur",
        "Max Global Output": "Sortie Globale Max",
        "Resource Inputs": "Entrées Ressources",
        "Production Lines": "Lignes de Production",
        "Factory Overview": "Aperçu Usine",
        "Tap to Plan Production": "Toucher pour Planifier",
        "Total Power": "Puissance Totale",
        "Buildings": "Bâtiments",
        "PRODUCTION STATUS: ONLINE": "STATUT PRODUCTION: EN LIGNE",
        "Add Product Goal": "Ajouter Objectif Produit",
        "Add Resource Input": "Ajouter Entrée Ressource",

        // PRODUCTION INPUT
        "PRODUCTION PLANNER": "PLANIFICATEUR PRODUCTION",
        "NEW PRODUCTION LINE": "NOUVELLE LIGNE",
        "Target Product": "Produit Cible",
        "Select Item to Produce...": "Sélectionner Item...",
        "Production Parameters": "Paramètres Production",
        "Desired Output Rate": "Taux de Sortie Désiré",
        "Allow Alternate Recipes": "Autoriser Recettes Alternatives",
        "Projected Requirements": "Besoins Estimés",
        "Estimated Input Materials": "Matériaux d'Entrée Estimés",
        "Smelters": "Fonderies",
        "Add to Project": "Ajouter au Projet",
        "Blueprint": "Plan",
        "Blueprint Details": "Détails du Plan",
        "Description": "Description",
        "Save Blueprint": "Sauver Plan"
    ]

    static func translate(_ key: String) -> String {
        return map[key] ?? key
    }
}
